const TROLL_EMOJI_ID = '1404841818176356515'
const TEAM_NAME = 'TROLLS!';
const TEAM_SHORT_VENUE = '4Bs';
const TEAM_WITH_VENUE = `${TEAM_SHORT_VENUE} ${TEAM_NAME}`;

module.exports = {
	TROLL_EMOJI_ID,
	TEAM_NAME,
	TEAM_SHORT_VENUE,
	TEAM_WITH_VENUE
}
